version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Gather dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Create test output directory
          command: mkdir ./junit
      - run:
          name: Test
          command: npm run test
  publish:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache:
          keys:
            - lib-cache-
      - run:
          name: Configure NPM
          command: printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run:
          name: Publish to NPM
          command: npm publish --access restricted

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              ignore: /^release.*/
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - publish:
          context: org-global
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v\d+.\d+.\d+/
